apiVersion: v1
kind: Service
metadata:
  name: apiserver
spec:
  ports:
    - name: grpc
      port: 8000
    - name: raft
      port: 4000
  clusterIP: None
  selector:
    app: apiserver

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apiserver
spec:
  serviceName: "apiserver"
  replicas: 2
  selector:
    matchLabels:
      app: apiserver
  template:
    metadata:
      labels:
        app: apiserver
    spec:
      containers:
        - name: nanobox
          image: phonghmnguyen/apiserver:linux-amd64
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 8000
            - name: raft
              containerPort: 4000
          volumeMounts:
            - name: raftdir
              mountPath: /raftdir
          env:
            - name: ORDINAL_NUMBER
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['apps.kubernetes.io/pod-index']
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_NAME
              value: "apiserver"
  volumeClaimTemplates:
    - metadata:
        name: raftdir
      spec:
        accessModes: [ReadWriteOnce]
        storageClassName: fast-disks
        resources:
          requests:
            storage: 1Gi
