// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: nbox/nbox.proto

package nbox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Error int32

const (
	Error_OK        Error = 0
	Error_NOTMASTER Error = 1
)

// Enum value maps for Error.
var (
	Error_name = map[int32]string{
		0: "OK",
		1: "NOTMASTER",
	}
	Error_value = map[string]int32{
		"OK":        0,
		"NOTMASTER": 1,
	}
)

func (x Error) Enum() *Error {
	p := new(Error)
	*p = x
	return p
}

func (x Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Error) Descriptor() protoreflect.EnumDescriptor {
	return file_nbox_nbox_proto_enumTypes[0].Descriptor()
}

func (Error) Type() protoreflect.EnumType {
	return &file_nbox_nbox_proto_enumTypes[0]
}

func (x Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Error.Descriptor instead.
func (Error) EnumDescriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{0}
}

type Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key          string                     `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value        []byte                     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	LastUpdated  *timestamppb.Timestamp     `protobuf:"bytes,3,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	CreationTime *timestamppb.Timestamp     `protobuf:"bytes,4,opt,name=creationTime,proto3" json:"creationTime,omitempty"`
	ExpiryTime   *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=expiryTime,proto3" json:"expiryTime,omitempty"`
	Ttl          *durationpb.Duration       `protobuf:"bytes,6,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Metadata     map[string]*structpb.Value `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Entry) Reset() {
	*x = Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{0}
}

func (x *Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Entry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Entry) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *Entry) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

func (x *Entry) GetExpiryTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryTime
	}
	return nil
}

func (x *Entry) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *Entry) GetMetadata() map[string]*structpb.Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type MasterInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MasterInfoRequest) Reset() {
	*x = MasterInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterInfoRequest) ProtoMessage() {}

func (x *MasterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterInfoRequest.ProtoReflect.Descriptor instead.
func (*MasterInfoRequest) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{1}
}

type MasterInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FQDN string `protobuf:"bytes,1,opt,name=FQDN,proto3" json:"FQDN,omitempty"`
	ID   uint32 `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *MasterInfoResponse) Reset() {
	*x = MasterInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterInfoResponse) ProtoMessage() {}

func (x *MasterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterInfoResponse.ProtoReflect.Descriptor instead.
func (*MasterInfoResponse) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{2}
}

func (x *MasterInfoResponse) GetFQDN() string {
	if x != nil {
		return x.FQDN
	}
	return ""
}

func (x *MasterInfoResponse) GetID() uint32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type GetOrPeakRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetOrPeakRequest) Reset() {
	*x = GetOrPeakRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrPeakRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrPeakRequest) ProtoMessage() {}

func (x *GetOrPeakRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrPeakRequest.ProtoReflect.Descriptor instead.
func (*GetOrPeakRequest) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrPeakRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetOrPeakResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entry *Entry `protobuf:"bytes,1,opt,name=entry,proto3,oneof" json:"entry,omitempty"`
	Flag  bool   `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *GetOrPeakResponse) Reset() {
	*x = GetOrPeakResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOrPeakResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrPeakResponse) ProtoMessage() {}

func (x *GetOrPeakResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrPeakResponse.ProtoReflect.Descriptor instead.
func (*GetOrPeakResponse) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrPeakResponse) GetEntry() *Entry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *GetOrPeakResponse) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

type SetOrUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetOrUpdateRequest) Reset() {
	*x = SetOrUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOrUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrUpdateRequest) ProtoMessage() {}

func (x *SetOrUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrUpdateRequest.ProtoReflect.Descriptor instead.
func (*SetOrUpdateRequest) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{5}
}

func (x *SetOrUpdateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetOrUpdateRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type SetOrUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag  bool  `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
	Error Error `protobuf:"varint,2,opt,name=error,proto3,enum=nbox.Error" json:"error,omitempty"`
}

func (x *SetOrUpdateResponse) Reset() {
	*x = SetOrUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOrUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOrUpdateResponse) ProtoMessage() {}

func (x *SetOrUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOrUpdateResponse.ProtoReflect.Descriptor instead.
func (*SetOrUpdateResponse) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{6}
}

func (x *SetOrUpdateResponse) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *SetOrUpdateResponse) GetError() Error {
	if x != nil {
		return x.Error
	}
	return Error_OK
}

type DeleteOrPurgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key *string `protobuf:"bytes,1,opt,name=key,proto3,oneof" json:"key,omitempty"`
}

func (x *DeleteOrPurgeRequest) Reset() {
	*x = DeleteOrPurgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOrPurgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrPurgeRequest) ProtoMessage() {}

func (x *DeleteOrPurgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrPurgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrPurgeRequest) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteOrPurgeRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

type DeleteOrPurgeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag  *bool `protobuf:"varint,1,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	Error Error `protobuf:"varint,2,opt,name=error,proto3,enum=nbox.Error" json:"error,omitempty"`
}

func (x *DeleteOrPurgeResponse) Reset() {
	*x = DeleteOrPurgeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOrPurgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrPurgeResponse) ProtoMessage() {}

func (x *DeleteOrPurgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrPurgeResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrPurgeResponse) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteOrPurgeResponse) GetFlag() bool {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return false
}

func (x *DeleteOrPurgeResponse) GetError() Error {
	if x != nil {
		return x.Error
	}
	return Error_OK
}

type KeysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KeysRequest) Reset() {
	*x = KeysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysRequest) ProtoMessage() {}

func (x *KeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysRequest.ProtoReflect.Descriptor instead.
func (*KeysRequest) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{9}
}

type KeysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keys []string `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
}

func (x *KeysResponse) Reset() {
	*x = KeysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeysResponse) ProtoMessage() {}

func (x *KeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeysResponse.ProtoReflect.Descriptor instead.
func (*KeysResponse) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{10}
}

func (x *KeysResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type EntriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EntriesRequest) Reset() {
	*x = EntriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntriesRequest) ProtoMessage() {}

func (x *EntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntriesRequest.ProtoReflect.Descriptor instead.
func (*EntriesRequest) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{11}
}

type EntriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *EntriesResponse) Reset() {
	*x = EntriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntriesResponse) ProtoMessage() {}

func (x *EntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntriesResponse.ProtoReflect.Descriptor instead.
func (*EntriesResponse) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{12}
}

func (x *EntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SizeOrCapRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SizeOrCapRequest) Reset() {
	*x = SizeOrCapRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeOrCapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeOrCapRequest) ProtoMessage() {}

func (x *SizeOrCapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeOrCapRequest.ProtoReflect.Descriptor instead.
func (*SizeOrCapRequest) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{13}
}

type SizeOrCapResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *SizeOrCapResponse) Reset() {
	*x = SizeOrCapResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SizeOrCapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeOrCapResponse) ProtoMessage() {}

func (x *SizeOrCapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeOrCapResponse.ProtoReflect.Descriptor instead.
func (*SizeOrCapResponse) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{14}
}

func (x *SizeOrCapResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type DefaultTTLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DefaultTTLRequest) Reset() {
	*x = DefaultTTLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultTTLRequest) ProtoMessage() {}

func (x *DefaultTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultTTLRequest.ProtoReflect.Descriptor instead.
func (*DefaultTTLRequest) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{15}
}

type DefaultTTLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ttl *durationpb.Duration `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *DefaultTTLResponse) Reset() {
	*x = DefaultTTLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultTTLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultTTLResponse) ProtoMessage() {}

func (x *DefaultTTLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultTTLResponse.ProtoReflect.Descriptor instead.
func (*DefaultTTLResponse) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{16}
}

func (x *DefaultTTLResponse) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type ResizeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size int64 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
}

func (x *ResizeRequest) Reset() {
	*x = ResizeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeRequest) ProtoMessage() {}

func (x *ResizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeRequest.ProtoReflect.Descriptor instead.
func (*ResizeRequest) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{17}
}

func (x *ResizeRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ResizeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error Error `protobuf:"varint,1,opt,name=error,proto3,enum=nbox.Error" json:"error,omitempty"`
}

func (x *ResizeResponse) Reset() {
	*x = ResizeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeResponse) ProtoMessage() {}

func (x *ResizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeResponse.ProtoReflect.Descriptor instead.
func (*ResizeResponse) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{18}
}

func (x *ResizeResponse) GetError() Error {
	if x != nil {
		return x.Error
	}
	return Error_OK
}

type UpdateDefaultTTLRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ttl *durationpb.Duration `protobuf:"bytes,1,opt,name=ttl,proto3" json:"ttl,omitempty"`
}

func (x *UpdateDefaultTTLRequest) Reset() {
	*x = UpdateDefaultTTLRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDefaultTTLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefaultTTLRequest) ProtoMessage() {}

func (x *UpdateDefaultTTLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefaultTTLRequest.ProtoReflect.Descriptor instead.
func (*UpdateDefaultTTLRequest) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateDefaultTTLRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type UpdateDefaultTTLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error Error `protobuf:"varint,1,opt,name=error,proto3,enum=nbox.Error" json:"error,omitempty"`
}

func (x *UpdateDefaultTTLResponse) Reset() {
	*x = UpdateDefaultTTLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nbox_nbox_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDefaultTTLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDefaultTTLResponse) ProtoMessage() {}

func (x *UpdateDefaultTTLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nbox_nbox_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDefaultTTLResponse.ProtoReflect.Descriptor instead.
func (*UpdateDefaultTTLResponse) Descriptor() ([]byte, []int) {
	return file_nbox_nbox_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateDefaultTTLResponse) GetError() Error {
	if x != nil {
		return x.Error
	}
	return Error_OK
}

var File_nbox_nbox_proto protoreflect.FileDescriptor

var file_nbox_nbox_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6e, 0x62, 0x6f, 0x78, 0x2f, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6e, 0x62, 0x6f, 0x78, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2, 0x03, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x3c, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x3e, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3a, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12,
	0x35, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x2e, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x53, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x13, 0x0a, 0x11, 0x4d,
	0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x38, 0x0a, 0x12, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x51, 0x44, 0x4e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x51, 0x44, 0x4e, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x49, 0x44, 0x22, 0x24, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x50, 0x65, 0x61, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x22, 0x59, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x50, 0x65, 0x61, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x88, 0x01, 0x01, 0x12, 0x12, 0x0a,
	0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x6c, 0x61,
	0x67, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x22, 0x3c, 0x0a, 0x12, 0x53,
	0x65, 0x74, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4c, 0x0a, 0x13, 0x53, 0x65, 0x74,
	0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x66, 0x6c, 0x61, 0x67, 0x12, 0x21, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4f, 0x72, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x15, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6b, 0x65, 0x79, 0x22, 0x5c,
	0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x88, 0x01, 0x01,
	0x12, 0x21, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0b, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x66, 0x6c, 0x61, 0x67, 0x22, 0x0d, 0x0a, 0x0b,
	0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x22, 0x0a, 0x0c, 0x4b,
	0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x65, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x65, 0x79, 0x73, 0x22,
	0x10, 0x0a, 0x0e, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x38, 0x0a, 0x0f, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x53,
	0x69, 0x7a, 0x65, 0x4f, 0x72, 0x43, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x27, 0x0a, 0x11, 0x53, 0x69, 0x7a, 0x65, 0x4f, 0x72, 0x43, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x41, 0x0a,
	0x12, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x74, 0x74, 0x6c,
	0x22, 0x23, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x33, 0x0a, 0x0e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x46, 0x0a, 0x17, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2b, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x74,
	0x74, 0x6c, 0x22, 0x3d, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e,
	0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x2a, 0x1e, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b,
	0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x4d, 0x41, 0x53, 0x54, 0x45, 0x52, 0x10,
	0x01, 0x32, 0xfc, 0x06, 0x0a, 0x07, 0x4e, 0x61, 0x6e, 0x6f, 0x62, 0x6f, 0x78, 0x12, 0x45, 0x0a,
	0x0e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x12,
	0x17, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e,
	0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x6e, 0x62,
	0x6f, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x50, 0x65, 0x61, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x50, 0x65, 0x61, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39,
	0x0a, 0x04, 0x50, 0x65, 0x65, 0x6b, 0x12, 0x16, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x47, 0x65,
	0x74, 0x4f, 0x72, 0x50, 0x65, 0x61, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17,
	0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x50, 0x65, 0x61, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x03, 0x53, 0x65, 0x74,
	0x12, 0x18, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x74, 0x4f, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x6e, 0x62, 0x6f,
	0x78, 0x2e, 0x53, 0x65, 0x74, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x18, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x65, 0x74, 0x4f, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6e, 0x62,
	0x6f, 0x78, 0x2e, 0x53, 0x65, 0x74, 0x4f, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x1a, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f,
	0x72, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e,
	0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x72, 0x50, 0x75, 0x72,
	0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x05,
	0x50, 0x75, 0x72, 0x67, 0x65, 0x12, 0x1a, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x4f, 0x72, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f,
	0x72, 0x50, 0x75, 0x72, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x2f, 0x0a, 0x04, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x11, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e,
	0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6e, 0x62,
	0x6f, 0x78, 0x2e, 0x4b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x38, 0x0a, 0x07, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14, 0x2e, 0x6e,
	0x62, 0x6f, 0x78, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x04, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x16, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x4f,
	0x72, 0x43, 0x61, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e, 0x62,
	0x6f, 0x78, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x4f, 0x72, 0x43, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x38, 0x0a, 0x03, 0x43, 0x61, 0x70, 0x12, 0x16, 0x2e,
	0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x69, 0x7a, 0x65, 0x4f, 0x72, 0x43, 0x61, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x53, 0x69, 0x7a,
	0x65, 0x4f, 0x72, 0x43, 0x61, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x41, 0x0a, 0x0a, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x12, 0x17,
	0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x13, 0x2e,
	0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x52, 0x65, 0x73, 0x69, 0x7a, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x10, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x12, 0x1e,
	0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x1e,
	0x2e, 0x6e, 0x62, 0x6f, 0x78, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x54, 0x54, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x20, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70,
	0x68, 0x2d, 0x6e, 0x67, 0x6e, 0x2f, 0x6e, 0x61, 0x6e, 0x6f, 0x62, 0x6f, 0x78, 0x2f, 0x6e, 0x62,
	0x6f, 0x78, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nbox_nbox_proto_rawDescOnce sync.Once
	file_nbox_nbox_proto_rawDescData = file_nbox_nbox_proto_rawDesc
)

func file_nbox_nbox_proto_rawDescGZIP() []byte {
	file_nbox_nbox_proto_rawDescOnce.Do(func() {
		file_nbox_nbox_proto_rawDescData = protoimpl.X.CompressGZIP(file_nbox_nbox_proto_rawDescData)
	})
	return file_nbox_nbox_proto_rawDescData
}

var file_nbox_nbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nbox_nbox_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_nbox_nbox_proto_goTypes = []interface{}{
	(Error)(0),                       // 0: nbox.Error
	(*Entry)(nil),                    // 1: nbox.Entry
	(*MasterInfoRequest)(nil),        // 2: nbox.MasterInfoRequest
	(*MasterInfoResponse)(nil),       // 3: nbox.MasterInfoResponse
	(*GetOrPeakRequest)(nil),         // 4: nbox.GetOrPeakRequest
	(*GetOrPeakResponse)(nil),        // 5: nbox.GetOrPeakResponse
	(*SetOrUpdateRequest)(nil),       // 6: nbox.SetOrUpdateRequest
	(*SetOrUpdateResponse)(nil),      // 7: nbox.SetOrUpdateResponse
	(*DeleteOrPurgeRequest)(nil),     // 8: nbox.DeleteOrPurgeRequest
	(*DeleteOrPurgeResponse)(nil),    // 9: nbox.DeleteOrPurgeResponse
	(*KeysRequest)(nil),              // 10: nbox.KeysRequest
	(*KeysResponse)(nil),             // 11: nbox.KeysResponse
	(*EntriesRequest)(nil),           // 12: nbox.EntriesRequest
	(*EntriesResponse)(nil),          // 13: nbox.EntriesResponse
	(*SizeOrCapRequest)(nil),         // 14: nbox.SizeOrCapRequest
	(*SizeOrCapResponse)(nil),        // 15: nbox.SizeOrCapResponse
	(*DefaultTTLRequest)(nil),        // 16: nbox.DefaultTTLRequest
	(*DefaultTTLResponse)(nil),       // 17: nbox.DefaultTTLResponse
	(*ResizeRequest)(nil),            // 18: nbox.ResizeRequest
	(*ResizeResponse)(nil),           // 19: nbox.ResizeResponse
	(*UpdateDefaultTTLRequest)(nil),  // 20: nbox.UpdateDefaultTTLRequest
	(*UpdateDefaultTTLResponse)(nil), // 21: nbox.UpdateDefaultTTLResponse
	nil,                              // 22: nbox.Entry.MetadataEntry
	(*timestamppb.Timestamp)(nil),    // 23: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),      // 24: google.protobuf.Duration
	(*structpb.Value)(nil),           // 25: google.protobuf.Value
}
var file_nbox_nbox_proto_depIdxs = []int32{
	23, // 0: nbox.Entry.lastUpdated:type_name -> google.protobuf.Timestamp
	23, // 1: nbox.Entry.creationTime:type_name -> google.protobuf.Timestamp
	23, // 2: nbox.Entry.expiryTime:type_name -> google.protobuf.Timestamp
	24, // 3: nbox.Entry.ttl:type_name -> google.protobuf.Duration
	22, // 4: nbox.Entry.metadata:type_name -> nbox.Entry.MetadataEntry
	1,  // 5: nbox.GetOrPeakResponse.entry:type_name -> nbox.Entry
	0,  // 6: nbox.SetOrUpdateResponse.error:type_name -> nbox.Error
	0,  // 7: nbox.DeleteOrPurgeResponse.error:type_name -> nbox.Error
	1,  // 8: nbox.EntriesResponse.entries:type_name -> nbox.Entry
	24, // 9: nbox.DefaultTTLResponse.ttl:type_name -> google.protobuf.Duration
	0,  // 10: nbox.ResizeResponse.error:type_name -> nbox.Error
	24, // 11: nbox.UpdateDefaultTTLRequest.ttl:type_name -> google.protobuf.Duration
	0,  // 12: nbox.UpdateDefaultTTLResponse.error:type_name -> nbox.Error
	25, // 13: nbox.Entry.MetadataEntry.value:type_name -> google.protobuf.Value
	2,  // 14: nbox.Nanobox.DiscoverMaster:input_type -> nbox.MasterInfoRequest
	4,  // 15: nbox.Nanobox.Get:input_type -> nbox.GetOrPeakRequest
	4,  // 16: nbox.Nanobox.Peek:input_type -> nbox.GetOrPeakRequest
	6,  // 17: nbox.Nanobox.Set:input_type -> nbox.SetOrUpdateRequest
	6,  // 18: nbox.Nanobox.Update:input_type -> nbox.SetOrUpdateRequest
	8,  // 19: nbox.Nanobox.Delete:input_type -> nbox.DeleteOrPurgeRequest
	8,  // 20: nbox.Nanobox.Purge:input_type -> nbox.DeleteOrPurgeRequest
	10, // 21: nbox.Nanobox.Keys:input_type -> nbox.KeysRequest
	12, // 22: nbox.Nanobox.Entries:input_type -> nbox.EntriesRequest
	14, // 23: nbox.Nanobox.Size:input_type -> nbox.SizeOrCapRequest
	14, // 24: nbox.Nanobox.Cap:input_type -> nbox.SizeOrCapRequest
	16, // 25: nbox.Nanobox.DefaultTTL:input_type -> nbox.DefaultTTLRequest
	18, // 26: nbox.Nanobox.Resize:input_type -> nbox.ResizeRequest
	21, // 27: nbox.Nanobox.UpdateDefaultTTL:input_type -> nbox.UpdateDefaultTTLResponse
	3,  // 28: nbox.Nanobox.DiscoverMaster:output_type -> nbox.MasterInfoResponse
	5,  // 29: nbox.Nanobox.Get:output_type -> nbox.GetOrPeakResponse
	5,  // 30: nbox.Nanobox.Peek:output_type -> nbox.GetOrPeakResponse
	7,  // 31: nbox.Nanobox.Set:output_type -> nbox.SetOrUpdateResponse
	6,  // 32: nbox.Nanobox.Update:output_type -> nbox.SetOrUpdateRequest
	9,  // 33: nbox.Nanobox.Delete:output_type -> nbox.DeleteOrPurgeResponse
	9,  // 34: nbox.Nanobox.Purge:output_type -> nbox.DeleteOrPurgeResponse
	11, // 35: nbox.Nanobox.Keys:output_type -> nbox.KeysResponse
	13, // 36: nbox.Nanobox.Entries:output_type -> nbox.EntriesResponse
	15, // 37: nbox.Nanobox.Size:output_type -> nbox.SizeOrCapResponse
	15, // 38: nbox.Nanobox.Cap:output_type -> nbox.SizeOrCapResponse
	17, // 39: nbox.Nanobox.DefaultTTL:output_type -> nbox.DefaultTTLResponse
	19, // 40: nbox.Nanobox.Resize:output_type -> nbox.ResizeResponse
	21, // 41: nbox.Nanobox.UpdateDefaultTTL:output_type -> nbox.UpdateDefaultTTLResponse
	28, // [28:42] is the sub-list for method output_type
	14, // [14:28] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_nbox_nbox_proto_init() }
func file_nbox_nbox_proto_init() {
	if File_nbox_nbox_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nbox_nbox_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrPeakRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOrPeakResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOrUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOrUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOrPurgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOrPurgeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KeysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeOrCapRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SizeOrCapResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultTTLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultTTLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResizeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResizeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDefaultTTLRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nbox_nbox_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDefaultTTLResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_nbox_nbox_proto_msgTypes[4].OneofWrappers = []interface{}{}
	file_nbox_nbox_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_nbox_nbox_proto_msgTypes[8].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nbox_nbox_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nbox_nbox_proto_goTypes,
		DependencyIndexes: file_nbox_nbox_proto_depIdxs,
		EnumInfos:         file_nbox_nbox_proto_enumTypes,
		MessageInfos:      file_nbox_nbox_proto_msgTypes,
	}.Build()
	File_nbox_nbox_proto = out.File
	file_nbox_nbox_proto_rawDesc = nil
	file_nbox_nbox_proto_goTypes = nil
	file_nbox_nbox_proto_depIdxs = nil
}
